export const SEARCH_TEACHER = 'SEARCH_TEACHER';
export const SEARCH_TEACHERS = 'SEARCH_TEACHERS';
export const SEARCH_STUDENTS = 'SEARCH_STUDENTS';
export const SEARCH_STUDENT = 'SEARCH_STUDENT';
export const SEARCH_STUDENT_MARKS = 'SEARCH_STUDENT_MARKS';
export const SEARCH_PARENTS = 'SEARCH_PARENTS';
export const SEARCH_TESTS = 'SEARCH_TESTS';
export const SEARCH_NOTICES = 'SEARCH_NOTICES';
