export const SEARCH_TEACHER = 'SEARCH_TEACHER';
export const SEARCH_TEACHERS = 'SEARCH_TEACHERS';
export const ADD_PERSON = 'ADD_PERSON';
export const SEARCH_STUDENTS = 'SEARCH_STUDENTS';
export const SEARCH_STUDENT = 'SEARCH_STUDENT';
export const SEARCH_STUDENT_MARKS = 'SEARCH_STUDENT_MARKS';
export const SEARCH_PARENTS = 'SEARCH_PARENTS';
export const SEARCH_PARENT = 'SEARCH_PARENT';
export const SEARCH_TESTS = 'SEARCH_TESTS';
export const SEARCH_TEST_NOTICES = 'SEARCH_TEST_NOTICES'; 
export const SEARCH_MISSED_TESTS = 'SEARCH_MISSED_TESTS';
export const SEARCH_NOTICES = 'SEARCH_NOTICES';
export const SEARCH_EVENTS = 'SEARCH_EVENTS';
export const SEARCH_ASSESSMENTS = 'SEARCH_ASSESSMENTS';
export const ADD_NOTICE = 'ADD_NOTICE';
export const SEARCH_CASES = 'SEARCH_CASES';
export const SEARCH_PERSON_AUTH = 'SEARCH_PERSON_AUTH';
export const SET_AUTH_TEACHER = 'SET_AUTH_TEACHER';
export const SET_AUTH_ADMIN = 'SET_AUTH_ADMIN';
export const SET_AUTH_STUDENT = 'SET_AUTH_STUDENT'
export const STOP_SESSION = 'STOP_SESSION';
export const RESET_STATE = 'RESET_STATE';
export const ADD_TEST_NOTICE = 'ADD_TEST_NOTICE';
export const ADD_EVENT = 'ADD_EVENT';
export const ADD_STUDENT_CASE = 'ADD_STUDENT_CASE';
export const ADD_STUDENT_MARKS = 'ADD_STUDENT_MARKS';
export const ADD_ASSESSMENT = 'ADD_ASSESSMENT';
export const ADD_MISSED_TEST = 'ADD_MISSED_TEST';
export const UPDATE_PERSON = 'UPDATE_PERSON';
export const SEND_MARKS = 'SEND_MARKS';
export const ASSESSMENT_PRIVILEGE = 'ASSESSMENT_PRIVILEGE';
export const RESET_MARKS = 'RESET_MARKS';
export const DELETE_NOTICE = 'DELETE_NOTICE';
export const UPDATE_STUDENT_MARK = 'UPDATE_STUDENT_MARK';
export const STOP_SPINNER = 'STOP_SPINNER';



